apiVersion: apps/v1
kind: Deployment
metadata:
  name: myp
  labels:
    app: myp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myp
  template:
    metadata:
      labels:
        app: myp
    spec:
      containers:
        - name: myp
          image: username/myp:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5